- name: "Create kirppu group to facilitate access to static files"
  group: name=kirppu system=yes

- name: "Add the nginx user to the kirppu group"
  user: name=nginx groups=kirppu append=yes

- name: "Create host data directory"
  file: path=/srv/{{ kirppu_hostname }} state=directory owner=root group=kirppu mode=02710

- name: "Create static files directory"
  file: path=/srv/{{ kirppu_hostname }}/public_html state=directory owner=root group=kirppu mode=02750

- name: "Setup nginx vhost for {{ kirppu_hostname }}"
  template: src=kirppu.nginx.j2 dest=/etc/nginx/sites-available/{{ kirppu_hostname }} mode=0644
  notify: restart nginx
  tags: [kirppu-nginx]

- name: "Enable nginx vhost for {{ kirppu_hostname }}"
  file: >
    src=/etc/nginx/sites-available/{{ kirppu_hostname }}
    path=/etc/nginx/sites-enabled/{{ kirppu_hostname }}
    state=link
  notify: restart nginx
  tags: [kirppu-nginx]

- name: "Update kirppu docker image from the registry"
  docker_image:
    name: tracon/kirppu
    force: yes
  tags: [kirppu-deploy]

- name: "Create kirppu container for {{ kirppu_hostname }}"
  docker_container:
    name: "{{ kirppu_hostname }}"
    image: tracon/kirppu
    recreate: yes
    restart_policy: unless-stopped
    command: "gunicorn --bind=0.0.0.0:8000 --workers={{ kirppu_workers }} kirppu_project.wsgi:application"
    ports:
      - "127.0.0.1:{{ kirppu_port }}:8000"
    links:
      - "{{ kirppu_postgresql_container }}:postgres"
    env:
      ADMINS: "{{ kirppu_admins }}"
      ALLOWED_HOSTS: "{{ kirppu_allowed_hosts }}"
      DATABASE_URL: "postgres://{{ kirppu_postgresql_username }}:{{ kirppu_postgresql_password }}@postgres/{{ kirppu_postgresql_database }}"
      DEFAULT_FROM_EMAIL: "{{ kirppu_default_from_email }}"
      EMAIL_HOST: "{{ kirppu_email_host }}"
      KOMPASSI_OAUTH2_CLIENT_ID: "{{ kirppu_kompassi_oauth2_client_id }}"
      KOMPASSI_OAUTH2_CLIENT_SECRET: "{{ kirppu_kompassi_oauth2_client_secret }}"
      PROFILE_URL: "https://kompassi.eu/profile"
      LOGIN_URL: "/oauth2/login"
      LOGOUT_URL: "/oauth2/logout"
      KIRPPU_USE_SSO: "1"
      LANGUAGES: "{{ kirppu_languages }}"
      SECRET_KEY: "{{ kirppu_secret_key }}"
      KIRPPU_REGISTER_ACTIVE_UNTIL: "{{ kirppu_registration_end }}"
      KIRPPU_CHECKOUT_ACTIVE: "{{ kirppu_checkout_active }}"
  tags: [kirppu-deploy]

- name: "Extract static files from inside container (command version)"
  command: >
    /usr/bin/docker cp {{ kirppu_hostname }}:/usr/src/app/static /srv/{{ kirppu_hostname }}/public_html/
  tags: [kirppu-deploy]
