- name: "Setup nginx vhost for {{ kirppu_hostname }}"
  template: src=kirppu.nginx.j2 dest=/etc/nginx/sites-available/{{ kirppu_hostname }} mode=0644
  notify: restart nginx
  tags: [kirppu-nginx]

- name: "Enable nginx vhost for {{ kirppu_hostname }}"
  file: >
    src=/etc/nginx/sites-available/{{ kirppu_hostname }}
    path=/etc/nginx/sites-enabled/{{ kirppu_hostname }}
    state=link
  notify: restart nginx
  tags: [kirppu-nginx]

- name: "Update kirppu docker image from the registry"
  docker_image:
    name: tracon/kirppu
    force: yes
  tags: [kirppu-deploy]

- name: "Create kirppu container for {{ kirppu_hostname }}"
  docker_container:
    name: "{{ kirppu_hostname }}"
    image: tracon/kirppu
    recreate: yes
    restart_policy: unless-stopped
    command: "gunicorn --bind=0.0.0.0:8000 --workers={{ kirppu_workers }} kirppu.wsgi:application"
    ports:
      - "{{ kirppu_port }}:8000"
    links:
      - "{{ kirppu_postgresql_container }}:postgres"
    env:
      ADMINS: "{{ kirppu_admins }}"
      ALLOWED_HOSTS: "{{ kirppu_allowed_hosts }}"
      DATABASE_URL: "postgres://{{ kirppu_postgresql_username }}:{{ kirppu_postgresql_password }}@postgres/{{ kirppu_postgresql_database }}"
      DEFAULT_FROM_EMAIL: "{{ kirppu_default_from_email }}"
      EMAIL_HOST: "{{ kirppu_email_host }}"
      KOMPASSI_CROWD_APPLICATION_NAME: "{{ kirppu_crowd_application_name }}"
      KOMPASSI_CROWD_APPLICATION_PASSWORD: "{{ kirppu_crowd_application_password }}"
      KOMPASSI_OAUTH2_CLIENT_ID: "{{ kirppu_kompassi_oauth2_client_id }}"
      KOMPASSI_OAUTH2_CLIENT_SECRET: "{{ kirppu_kompassi_oauth2_client_secret }}"
      SECRET_KEY: "{{ kirppu_secret_key }}"
  tags: [kirppu-deploy]

- name: "Extract static files from inside container (command version)"
  command: >
    /usr/bin/docker cp {{ kirppu_hostname }}-gunicorn:/usr/src/app/static /srv/{{ kirppu_hostname }}/public_html/
  tags: [kirppu-deploy]
