- hosts: docker_servers
  gather_facts: yes
  roles:
    - role: base
      tags: [base]
    - role: node-exporter
      tags: [node-exporter]
    - role: docker
      tags: [docker]
    - role: prebackup
      tags: [prebackup]
    - role: nginx
      tags: [nginx]

- hosts: postgresql_servers
  gather_facts: yes
  roles:
    - role: base
      tags: [base]
    - role: node-exporter
      tags: [node-exporter]
    - role: prebackup
      tags: [prebackup]
    - role: nginx
      tags: [nginx]

    - role: postgresql
      tags: [postgresql]

    - role: letsencrypt
      tags: [letsencrypt]
      letsencrypt_domains:
        # ugly
        - name: siilo.tracon.fi
          subject_alt_name: "DNS:siilo.tracon.fi"

    # default site
    - role: redirect
      tags: [redirect]
      redirect_default: true
      redirect_hostname: "{{ inventory_hostname }}"
      redirect_allowed_hosts: "{{ inventory_hostname }}"
      redirect_target: https://2020.tracon.fi
      redirect_ssl_certificate: /srv/letsencrypt/secrets/siilo.tracon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/siilo.tracon.fi/domain.key

- hosts: barman_servers
  gather_facts: yes
  roles:
    - role: base
      tags: [base]
    - role: node-exporter
      tags: [node-exporter]
    - role: postgresql-barman
      tags: [postgresql-barman]

- hosts: kompassi_servers
  gather_facts: yes
  roles:
    # default site
    - role: redirect
      tags: [redirect]
      redirect_hostname: "{{ inventory_hostname }}"
      redirect_allowed_hosts: "{{ inventory_hostname }} www.{{ inventory_hostname }}"
      redirect_target: https://kompassi.eu
      redirect_default: true
      redirect_ssl_certificate: /srv/letsencrypt/secrets/kompassi.eu/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/kompassi.eu/domain.key

    - role: redirect
      tags: [redirect]
      redirect_hostname: kompassi.tracon.fi
      redirect_allowed_hosts: kompassi.tracon.fi
      redirect_target: https://kompassi.eu
      redirect_ssl_certificate: /srv/letsencrypt/secrets/atlasso.tracon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/atlasso.tracon.fi/domain.key

    - role: redirect
      tags: [redirect]
      redirect_hostname: "www.animecon.fi"
      redirect_allowed_hosts: "www.animecon.fi"
      redirect_target: https://animecon.fi
      redirect_ssl_certificate: /srv/letsencrypt/secrets/kompassi.eu/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/kompassi.eu/domain.key

    - role: redirect
      tags: [redirect]
      redirect_hostname: "www.conit.fi"
      redirect_allowed_hosts: "www.conit.fi"
      redirect_target: https://conit.fi
      redirect_ssl_certificate: /srv/letsencrypt/secrets/kompassi.eu/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/kompassi.eu/domain.key

    - role: redirect
      tags: [redirect]
      redirect_hostname: "paikkaliput.tracon.fi"
      redirect_allowed_hosts: "paikkaliput.tracon.fi"
      redirect_target: https://kompassi.eu/profile/reservations
      redirect_ssl_certificate: /srv/letsencrypt/secrets/atlasso.tracon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/atlasso.tracon.fi/domain.key

    - role: postgresql-docker
      tags: [postgresql-docker]
      postgresql_hostname: kompassi.eu
      postgresql_username: kompassi
      postgresql_password: "{{ kompassi_postgresql_password }}"
      postgresql_database: kompassi
      postgresql_ssl_certificate: /srv/letsencrypt/secrets/kompassi.eu/chained.pem
      postgresql_ssl_certificate_key: /srv/letsencrypt/secrets/kompassi.eu/domain.key

    - role: kompassi
      kompassi_hostname: kompassi.eu
      tags:
        - kompassi
        - kompassi-production

    - role: kompassi2
      tags:
        - kompassi2
        - kompassi2-production

    - role: atlasso
      tags: [atlasso]
    - role: shoottikala
      tags: [shoottikala]

    - role: letsencrypt
      tags: [letsencrypt]
      letsencrypt_domains:
        - name: kompassi.eu
          subject_alt_name: "DNS:kompassi.eu,DNS:www.kompassi.eu,DNS:neula.kompassi.eu,DNS:v2.kompassi.eu,DNS:animecon.fi,DNS:www.animecon.fi,DNS:conit.fi,DNS:www.conit.fi"
        - name: photoshoot.conikuvat.fi
          subject_alt_name: "DNS:photoshoot.conikuvat.fi"

        # bad name, but use this for all *.tracon.fi that run on neula
        - name: atlasso.tracon.fi
          subject_alt_name: "DNS:atlasso.tracon.fi,DNS:kompassi.tracon.fi,DNS:paikkaliput.tracon.fi"

- hosts: management_servers
  gather_facts: yes
  roles:
    - role: jenkins
      tags: [jenkins]

    - role: postgresql-docker
      tags: [postgresql-docker]
      postgresql_hostname: jenkins.tracon.fi
      postgresql_username: jenkinslave
      postgresql_password: "{{ jenkinslave_postgresql_password }}"
      postgresql_database: test_kompassi
      postgresql_ssl_certificate: /srv/letsencrypt/secrets/monokkeli.tracon.fi/chained.pem
      postgresql_ssl_certificate_key: /srv/letsencrypt/secrets/monokkeli.tracon.fi/domain.key

    - role: jenkinslave
      tags: [jenkinslave]

    - role: prometheus
      tags: [prometheus]

    # get SSL for future service
    - role: redirect
      tags: [redirect]
      redirect_hostname: kibana.tracon.fi
      redirect_allowed_hosts: kibana.tracon.fi
      redirect_target: https://tracon.fi
      redirect_ssl: false
      redirect_letsencrypt: true
      redirect_ssl_certificate: /srv/letsencrypt/secrets/monokkeli.tracon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/monokkeli.tracon.fi/domain.key

    - role: letsencrypt
      tags: [letsencrypt]
      letsencrypt_domains:
        - name: monokkeli.tracon.fi
          subject_alt_name: "DNS:jenkins.tracon.fi,DNS:kibana.tracon.fi,DNS:grafana.tracon.fi,DNS:prometheus.tracon.fi,DNS:alertmanager.tracon.fi,DNS:pgadmin.monokkeli.tracon.fi"


- hosts: hop_servers
  gather_facts: yes
  roles:
    - role: base
      tags: [base]
      nameservers:
        - 8.8.8.8
        - 8.8.4.4

    - role: node-exporter
      tags: [node-exporter]

    - role: prebackup
      tags: [prebackup]

    - role: nginx
      tags: [nginx]

    - role: redirect
      tags: [redirect]
      redirect_hostname: "{{ inventory_hostname }}"
      redirect_allowed_hosts: "{{ inventory_hostname }} www.{{ inventory_hostname }}"
      redirect_target: https://kompassi.eu
      redirect_default: true
      redirect_ssl_certificate: /srv/letsencrypt/secrets/putki.tracon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/putki.tracon.fi/domain.key

    - role: proxy
      tags: [proxy]
      proxy_hostname: vara.kompassi.eu

      # nuoli.kompassi.eu
      proxy_target: https://91.105.251.77

      proxy_ssl_certificate: /srv/letsencrypt/secrets/vara.kompassi.eu/chained.pem
      proxy_ssl_certificate_key: /srv/letsencrypt/secrets/vara.kompassi.eu/domain.key

    - role: letsencrypt
      tags: [letsencrypt]
      letsencrypt_domains:
        - name: putki.tracon.fi
          subject_alt_name: "DNS:putki.tracon.fi"
        - name: vara.kompassi.eu
          subject_alt_name: "DNS:vara.kompassi.eu"

- hosts: atlassian_servers
  gather_facts: yes
  roles:
    - role: atlassian
      tags: [atlassian]

    - role: letsencrypt
      tags: [letsencrypt]
      letsencrypt_domains:
        - name: confluence.tracon.fi
          subject_alt_name: "DNS:confluence.tracon.fi,DNS:jira.tracon.fi,DNS:crowd.tracon.fi"

    - role: oidentd
      tags: [oidentd]
    - role: slackirc
      tags: [slackirc]