- hosts: all
  roles:
    - role: base
      tags: [base]

- hosts: docker-servers
  roles:
    - role: docker
      tags: [docker]
    - role: nginx
      tags: [nginx]

- hosts: logstash-centrals
  roles:
    - role: logstash-central
      tags: [logstash-central]
    - role: kibana
      tags: [kibana]

- hosts: rsyslog-to-logstash
  roles:
    - role: rsyslog-to-logstash
      tags: [rsyslog-to-logstash]

- hosts: postgresql-servers
  roles:
    - role: postgresql
      tags: [postgresql]

- hosts: tracon-servers
  roles:
    # default site
    - role: redirect
      tags: [redirect]
      redirect_hostname: "{{ inventory_hostname }}"
      redirect_allowed_hosts: "{{ inventory_hostname }} www.{{ inventory_hostname }}"
      redirect_target: https://2016.tracon.fi

    - role: redirect
      tags: [redirect]
      redirect_hostname: info-tv.tracon.fi
      redirect_allowed_hosts: info-tv.tracon.fi www.info-tv.tracon.fi
      redirect_target: https://infotv.tracon.fi

    - role: redirect
      tags: [redirect]
      redirect_hostname: infoloki.tracon.fi
      redirect_allowed_hosts: infoloki.tracon.fi www.infoloki.tracon.fi
      redirect_target: https://infokala.tracon.fi

    - role: redirect
      tags: [redirect]
      redirect_hostname: hitpoint.tracon.fi
      redirect_allowed_hosts: hitpoint.tracon.fi www.hitpoint.tracon.fi
      redirect_target: https://2015.hitpoint.tracon.fi

    - role: postgresql-docker
      tags: [postgresql-docker]
      postgresql_hostname: nuoli.tracon.fi
      postgresql_username: infokala
      postgresql_password: "{{ infokala_postgresql_password }}"
      postgresql_database: infokala

    # TODO instead of clumsy tracontent/tracontent-alias, split to tracontent-instance/tracontent-site
    - role: tracontent
      tags: [tracontent]
      tracontent_hostname: tracontent.tracon.fi
      tracontent_allowed_host_list:
        - 2016.tracon.fi
        - 2017.tracon.fi
        - blog.tracon.fi
        - r.tracon.fi
        - ry.tracon.fi
        - 2015.hitpoint.tracon.fi
        - 2016.hitpoint.tracon.fi
        - 2017.hitpoint.tracon.fi
      tracontent_nginx_server_name_list:
        - 2016.tracon.fi
        - 2017.tracon.fi
        - blog.tracon.fi
        - r.tracon.fi
        - ry.tracon.fi

    - role: tracontent-alias
      tags: [tracontent-alias]
      tracontent_alias_hostname: tracontent.hitpoint.tracon.fi
      tracontent_alias_nginx_server_name_list:
        - 2015.hitpoint.tracon.fi
        - 2016.hitpoint.tracon.fi
        - 2017.hitpoint.tracon.fi
      tracontent_alias_static_dir: /srv/tracontent.tracon.fi/public_html/static
      tracontent_alias_port: 8004
      tracontent_alias_ssl_certificate: /srv/letsencrypt/secrets/hitpoint.tracon.fi/chained.pem
      tracontent_alias_ssl_certificate_key: /srv/letsencrypt/secrets/hitpoint.tracon.fi/domain.key

    - role: infokala
      tags: [infokala]
    - role: infotv
      tags: [infotv]
    - role: slackirc
      tags: [slackirc]

    - role: letsencrypt
      tags: [letsencrypt]
      letsencrypt_domains:
        # ugly
        - name: tracon.fi
          subject_alt_name: "DNS:tracon.fi,DNS:www.tracon.fi,DNS:nuoli.tracon.fi,DNS:2016.tracon.fi,DNS:2017.tracon.fi,DNS:blog.tracon.fi,DNS:r.tracon.fi,DNS:ry.tracon.fi"
        - name: hitpoint.tracon.fi
          subject_alt_name: "DNS:hitpoint.tracon.fi,DNS:www.hitpoint.tracon.fi,DNS:2015.hitpoint.tracon.fi,DNS:2016.hitpoint.tracon.fi,DNS:2017.hitpoint.tracon.fi"
        - name: infotv.tracon.fi
          subject_alt_name: "DNS:infotv.tracon.fi,DNS:info-tv.tracon.fi"
        - name: infokala.tracon.fi
          subject_alt_name: "DNS:infokala.tracon.fi,DNS:infoloki.tracon.fi"

- hosts: kompassi-servers
  roles:
    # default site
    - role: redirect
      tags: [redirect]
      redirect_hostname: "{{ inventory_hostname }}"
      redirect_allowed_hosts: "{{ inventory_hostname }} www.{{ inventory_hostname }}"
      redirect_target: https://kompassi.eu
      redirect_ssl: false
      redirect_default: true

    - role: postgresql-docker
      tags: [postgresql-docker]
      postgresql_hostname: kompassi.eu
      postgresql_username: kompassi
      postgresql_password: "{{ kompassi_postgresql_password }}"
      postgresql_database: kompassi

    - role: kompassi
      tags: [kompassi]
    - role: atlasso
      tags: [atlasso]

    - role: letsencrypt
      tags: [letsencrypt]
      letsencrypt_domains:
        - name: kompassi.eu
          subject_alt_name: "DNS:kompassi.eu,DNS:www.kompassi.eu,DNS:neula.kompassi.eu"
        - name: atlasso.tracon.fi
          subject_alt_name: "DNS:atlasso.tracon.fi"

- hosts: management-servers
  roles:
    - role: jenkins
      tags: [jenkins]

    - role: postgresql-docker
      tags: [postgresql-docker]
      postgresql_hostname: jenkins.tracon.fi
      postgresql_username: jenkinslave
      postgresql_password: "{{ jenkinslave_postgresql_password }}"
      postgresql_database: test_kompassi

    - role: jenkinslave
      tags: [jenkinslave]
