- hosts: all
  roles:
    - role: base
      tags: [base]

- hosts: logstash-centrals
  roles:
    - role: logstash-central
      tags: [logstash-central]
    - role: kibana
      tags: [kibana]

- hosts: rsyslog-to-logstash
  roles:
    - role: rsyslog-to-logstash
      tags: [rsyslog-to-logstash]

- hosts: postgresql-servers
  roles:
    - role: base
      tags: [base]
    - role: postgresql
      tags: [postgresql]

- hosts: tracon-servers
  roles:
    - role: docker
      tags: [docker]
    - role: nginx
      tags: [nginx]
    # - role: infokala
      # tags: [infokala]
    - role: slackirc
      tags: [slackirc]

- hosts: kompassi-servers
  roles:
    - role: docker
      tags: [docker]
    - role: nginx
      tags: [nginx]
    - role: kompassi
      tags: [kompassi]
    - role: atlasso
      tags: [atlasso]

- hosts: management-servers
  roles:
    - role: docker
      tags: [docker]
    - role: nginx
      tags: [nginx]
    - role: jenkins
      tags: [jenkins]
