- hosts: docker_servers
  gather_facts: yes
  roles:
    - role: base
      tags: [base]
    - role: node-exporter
      tags: [node-exporter]
    - role: docker
      tags: [docker]
    - role: prebackup
      tags: [prebackup]
    - role: nginx
      tags: [nginx]

- hosts: postgresql_servers
  gather_facts: yes
  roles:
    - role: base
      tags: [base]
    - role: node-exporter
      tags: [node-exporter]
    - role: prebackup
      tags: [prebackup]
    - role: nginx
      tags: [nginx]

    - role: postgresql
      tags: [postgresql]

    - role: letsencrypt
      tags: [letsencrypt]
      letsencrypt_domains:
        # ugly
        - name: siilo.tracon.fi
          subject_alt_name: "DNS:siilo.tracon.fi"

    # default site
    - role: redirect
      tags: [redirect]
      redirect_default: true
      redirect_hostname: "{{ inventory_hostname }}"
      redirect_allowed_hosts: "{{ inventory_hostname }}"
      redirect_target: https://2020.tracon.fi
      redirect_ssl_certificate: /srv/letsencrypt/secrets/siilo.tracon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/siilo.tracon.fi/domain.key

- hosts: barman_servers
  gather_facts: yes
  roles:
    - role: base
      tags: [base]
    - role: node-exporter
      tags: [node-exporter]
    - role: postgresql-barman
      tags: [postgresql-barman]

- hosts: management_servers
  gather_facts: yes
  roles:
    - role: jenkins
      tags: [jenkins]

    - role: postgresql-docker
      tags: [postgresql-docker]
      postgresql_hostname: jenkins.tracon.fi
      postgresql_username: jenkinslave
      postgresql_password: "{{ jenkinslave_postgresql_password }}"
      postgresql_database: test_kompassi
      postgresql_ssl_certificate: /srv/letsencrypt/secrets/monokkeli.tracon.fi/chained.pem
      postgresql_ssl_certificate_key: /srv/letsencrypt/secrets/monokkeli.tracon.fi/domain.key

    - role: jenkinslave
      tags: [jenkinslave]

    - role: letsencrypt
      tags: [letsencrypt]
      letsencrypt_domains:
        - name: monokkeli.tracon.fi
          subject_alt_name: "DNS:jenkins.tracon.fi,DNS:monokkeli.tracon.fi"

- hosts: hop_servers
  gather_facts: yes
  roles:
    - role: base
      tags: [base]
      nameservers:
        - 8.8.8.8
        - 8.8.4.4

    - role: node-exporter
      tags: [node-exporter]

    - role: prebackup
      tags: [prebackup]

    - role: nginx
      tags: [nginx]

    - role: redirect
      tags: [redirect]
      redirect_hostname: "{{ inventory_hostname }}"
      redirect_allowed_hosts: "{{ inventory_hostname }} www.{{ inventory_hostname }}"
      redirect_target: https://kompassi.eu
      redirect_default: true
      redirect_ssl_certificate: /srv/letsencrypt/secrets/putki.tracon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/putki.tracon.fi/domain.key

    - role: proxy
      tags: [proxy]
      proxy_hostname: vara.kompassi.eu

      # nuoli.kompassi.eu
      proxy_target: https://91.105.251.77

      proxy_ssl_certificate: /srv/letsencrypt/secrets/vara.kompassi.eu/chained.pem
      proxy_ssl_certificate_key: /srv/letsencrypt/secrets/vara.kompassi.eu/domain.key

    - role: letsencrypt
      tags: [letsencrypt]
      letsencrypt_domains:
        - name: putki.tracon.fi
          subject_alt_name: "DNS:putki.tracon.fi"
        - name: vara.kompassi.eu
          subject_alt_name: "DNS:vara.kompassi.eu"

- hosts: atlassian_servers
  gather_facts: yes
  roles:
    - role: atlassian
      tags: [atlassian]

    - role: letsencrypt
      tags: [letsencrypt]
      letsencrypt_domains:
        - name: confluence.tracon.fi
          subject_alt_name: "DNS:confluence.tracon.fi,DNS:jira.tracon.fi,DNS:crowd.tracon.fi"

    - role: oidentd
      tags: [oidentd]
    - role: slackirc
      tags: [slackirc]
