- hosts: all
  roles:
    - role: base
      tags: [base]

- hosts: logstash-centrals
  roles:
    - role: logstash-central
      tags: [logstash-central]
    - role: kibana
      tags: [kibana]

- hosts: rsyslog-to-logstash
  roles:
    - role: rsyslog-to-logstash
      tags: [rsyslog-to-logstash]

- hosts: postgresql-servers
  roles:
    - role: base
      tags: [base]
    - role: postgresql
      tags: [postgresql]
  vars:
    ansible_python_interpreter: /usr/bin/python2.7

- hosts: nuoli.tracon.fi
  roles:
    - role: nodejs
      tags: [nodejs]
