- hosts: all
  roles:
    - role: base
      tags: [base]

- hosts: logstash-centrals
  roles:
    - role: logstash-central
      tags: [logstash-central]
    - role: kibana
      tags: [kibana]

- hosts: rsyslog-to-logstash
  roles:
    - role: rsyslog-to-logstash
      tags: [rsyslog-to-logstash]

- hosts: postgresql-servers
  roles:
    - role: base
      tags: [base]
    - role: postgresql
      tags: [postgresql]

- hosts: tracon-servers
  roles:
    - role: docker
      tags: [docker]
    - role: nginx
      tags: [nginx]
    - role: postgresql-docker
      tags: [postgresql-docker]
      postgresql_hostname: nuoli.tracon.fi
      postgresql_username: infokala
      postgresql_password: "{{ infokala_postgresql_password }}"
      postgresql_database: infokala
    - role: infokala
      tags: [infokala]
    - role: slackirc
      tags: [slackirc]

- hosts: kompassi-servers
  roles:
    - role: docker
      tags: [docker]
    - role: nginx
      tags: [nginx]
    - role: postgresql-docker
      tags: [postgresql-docker]
      postgresql_hostname: kompassi.eu
      postgresql_username: kompassi
      postgresql_password: "{{ kompassi_postgresql_password }}"
      postgresql_database: kompassi
    - role: kompassi
      tags: [kompassi]
    - role: atlasso
      tags: [atlasso]

- hosts: management-servers
  roles:
    - role: docker
      tags: [docker]
    - role: nginx
      tags: [nginx]
    - role: jenkins
      tags: [jenkins]
    - role: postgresql-docker
      tags: [postgresql-docker]
      postgresql_hostname: jenkins.tracon.fi
      postgresql_username: jenkinslave
      postgresql_password: "{{ jenkinslave_postgresql_password }}"
      postgresql_database: test_kompassi
    - role: jenkinslave
      tags: [jenkinslave]
