- hosts: docker-servers
  gather_facts: no
  roles:
    - role: base
      tags: [base]
    - role: node-exporter
      tags: [node-exporter]
    - role: docker
      tags: [docker]
    - role: prebackup
      tags: [prebackup]
    - role: nginx
      tags: [nginx]

- hosts: logstash-centrals
  gather_facts: no
  roles:
    - role: logstash-central
      tags: [logstash-central]
    - role: kibana
      tags: [kibana]

- hosts: legacy-servers
  gather_facts: yes
  roles:
    # - role: rsyslog-to-logstash
    #   tags: [rsyslog-to-logstash]
    - role: node-exporter
      tags: [node-exporter]

- hosts: postgresql-servers
  gather_facts: no
  roles:
    - role: base
      tags: [base]
    - role: postgresql
      tags: [postgresql]

- hosts: tracon-servers
  gather_facts: no
  roles:
    # default site
    - role: redirect
      tags: [redirect]
      redirect_default: true
      redirect_hostname: "{{ inventory_hostname }}"
      redirect_allowed_hosts: "{{ inventory_hostname }}"
      redirect_target: https://2017.tracon.fi
      redirect_ssl_certificate: /srv/letsencrypt/secrets/tracon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/tracon.fi/domain.key

    - role: redirect
      tags: [redirect]
      redirect_hostname: info-tv.tracon.fi
      redirect_allowed_hosts: info-tv.tracon.fi
      redirect_target: https://infotv.tracon.fi
      redirect_ssl_certificate: /srv/letsencrypt/secrets/infotv.tracon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/infotv.tracon.fi/domain.key

    - role: redirect
      tags: [redirect]
      redirect_hostname: infoloki.tracon.fi
      redirect_allowed_hosts: infoloki.tracon.fi
      redirect_target: https://infokala.tracon.fi
      redirect_ssl_certificate: /srv/letsencrypt/secrets/infokala.tracon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/infokala.tracon.fi/domain.key

    - role: redirect
      tags: [redirect]
      redirect_hostname: hitpoint.tracon.fi
      redirect_allowed_hosts: hitpoint.tracon.fi www.hitpoint.tracon.fi
      redirect_target: https://2017.hitpoint.tracon.fi
      redirect_ssl_certificate: /srv/letsencrypt/secrets/hitpoint.tracon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/hitpoint.tracon.fi/domain.key

    - role: redirect
      tags: [redirect]
      redirect_hostname: wiki.hitpoint.tracon.fi
      redirect_allowed_hosts: wiki.hitpoint.tracon.fi
      redirect_target: https://atlasso.tracon.fi/crowd?next=https://confluence.tracon.fi/display/HITPOINT2017
      redirect_ssl_certificate: /srv/letsencrypt/secrets/hitpoint.tracon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/hitpoint.tracon.fi/domain.key

    - role: redirect
      tags: [redirect]
      redirect_hostname: wiki.tracon.fi
      redirect_allowed_hosts: wiki.tracon.fi m.wiki.tracon.fi mwiki.tracon.fi
      redirect_target: https://atlasso.tracon.fi/crowd?next=https://confluence.tracon.fi/display/TRACON2017

    - role: redirect
      tags: [redirect]
      redirect_hostname: tyovoima.hitpoint.tracon.fi
      redirect_allowed_hosts: tyovoima.hitpoint.tracon.fi
      redirect_target: https://kompassi.eu/events/hitpoint2017/signup
      redirect_ssl_certificate: /srv/letsencrypt/secrets/hitpoint.tracon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/hitpoint.tracon.fi/domain.key

    - role: redirect
      tags: [redirect]
      redirect_hostname: tyovoima.tracon.fi
      redirect_allowed_hosts: tyovoima.tracon.fi
      redirect_target: https://kompassi.eu/events/tracon2017/signup
      redirect_ssl_certificate: /srv/letsencrypt/secrets/tracon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/tracon.fi/domain.key

    - role: redirect
      tags: [redirect]
      redirect_hostname: ohjelma.tracon.fi
      redirect_allowed_hosts: ohjelma.tracon.fi
      redirect_target: https://kompassi.eu/events/tracon11/programme
      redirect_ssl_certificate: /srv/letsencrypt/secrets/tracon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/tracon.fi/domain.key

    - role: redirect
      tags: [redirect]
      redirect_hostname: animecon.fi
      redirect_allowed_hosts: animecon.fi www.animecon.fi
      redirect_target: https://2016.animecon.fi
      redirect_ssl_certificate: /srv/letsencrypt/secrets/animecon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/animecon.fi/domain.key

    - role: redirect
      tags: [redirect]
      redirect_hostname: 2016.aicon.fi
      redirect_allowed_hosts: 2016.aicon.fi www.aicon.fi m.aicon.fi
      redirect_target: https://aicon.fi
      redirect_ssl_certificate: /srv/letsencrypt/secrets/aicon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/aicon.fi/domain.key

    - role: redirect
      tags: [redirect]
      redirect_hostname: kulukorvaus.tracon.fi
      redirect_allowed_hosts: kulukorvaus.tracon.fi
      redirect_target: https://atlasso.tracon.fi/crowd?next=https%3A%2F%2Fjira.tracon.fi%2Fsecure%2FCreateIssue.jspa%3Fpid%3D10900%26issuetype%3D10100
      redirect_ssl_certificate: /srv/letsencrypt/secrets/tracon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/tracon.fi/domain.key

    - role: redirect
      tags: [redirect]
      redirect_hostname: kulukorvaus.hitpoint.tracon.fi
      redirect_allowed_hosts: kulukorvaus.hitpoint.tracon.fi
      redirect_target: https://atlasso.tracon.fi/crowd?next=https%3A%2F%2Fjira.tracon.fi%2Fsecure%2FCreateIssue.jspa%3Fpid%3D10800%26issuetype%3D10100
      redirect_ssl_certificate: /srv/letsencrypt/secrets/hitpoint.tracon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/hitpoint.tracon.fi/domain.key

    - role: redirect
      tags: [redirect]
      redirect_hostname: kulukorvaus.ry.tracon.fi
      redirect_allowed_hosts: kulukorvaus.ry.tracon.fi
      redirect_target: https://atlasso.tracon.fi/crowd?next=https%3A%2F%2Fjira.tracon.fi%2Fsecure%2FCreateIssue.jspa%3Fpid%3D10302%26issuetype%3D10100
      redirect_ssl_certificate: /srv/letsencrypt/secrets/ry.tracon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/ry.tracon.fi/domain.key

    - role: postgresql-docker
      tags: [postgresql-docker]
      postgresql_hostname: nuoli.tracon.fi
      postgresql_username: infokala
      postgresql_password: "{{ infokala_postgresql_password }}"
      postgresql_database: infokala

    - role: tracontent
      tags: [tracontent]
      tracontent_setup_site: false
      tracontent_hostname: tracontent.tracon.fi
      tracontent_static_dir: /srv/tracontent.tracon.fi/public_html/static
      tracontent_allowed_host_list:
        - 2016.tracon.fi
        - 2017.tracon.fi
        - blog.tracon.fi
        - r.tracon.fi
        - ry.tracon.fi
        - 2015.hitpoint.tracon.fi
        - 2016.hitpoint.tracon.fi
        - 2017.hitpoint.tracon.fi
      tracontent_editor_group_list:
        - turska-hitpoint2017-labour-conitea
        - turska-tracon2017-labour-conitea
        - traconry-hallitus-nykyinen

    - role: tracontent
      tags: [tracontent]
      tracontent_setup_instance: false
      tracontent_hostname: tracontent.hitpoint.tracon.fi
      tracontent_allowed_host_list:
        - 2015.hitpoint.tracon.fi
        - 2016.hitpoint.tracon.fi
        - 2017.hitpoint.tracon.fi
      tracontent_static_dir: /srv/tracontent.tracon.fi/public_html/static
      tracontent_ssl_certificate: /srv/letsencrypt/secrets/hitpoint.tracon.fi/chained.pem
      tracontent_ssl_certificate_key: /srv/letsencrypt/secrets/hitpoint.tracon.fi/domain.key
      tracontent_favicon: null

    - role: tracontent
      tags: [tracontent]
      tracontent_setup_instance: false
      tracontent_hostname: tracontent.ry.tracon.fi
      tracontent_allowed_host_list:
        - ry.tracon.fi
      tracontent_static_dir: /srv/tracontent.tracon.fi/public_html/static
      tracontent_ssl_certificate: /srv/letsencrypt/secrets/ry.tracon.fi/chained.pem
      tracontent_ssl_certificate_key: /srv/letsencrypt/secrets/ry.tracon.fi/domain.key
      tracontent_favicon: null

    - role: tracontent
      tags: [tracontent]
      tracontent_setup_instance: false
      tracontent_hostname: tracontent.tracon.fi
      tracontent_allowed_host_list:
        - 2016.tracon.fi
        - 2017.tracon.fi
        - blog.tracon.fi
        - r.tracon.fi
      tracontent_static_dir: /srv/tracontent.tracon.fi/public_html/static
      tracontent_ssl_certificate: /srv/letsencrypt/secrets/tracon.fi/chained.pem
      tracontent_ssl_certificate_key: /srv/letsencrypt/secrets/tracon.fi/domain.key
      tracontent_favicon: null

    - role: tracontent
      tags: [tracontent]
      tracontent_hostname: tracontent.animecon.fi
      tracontent_static_dir: /srv/tracontent.animecon.fi/public_html/static
      tracontent_allowed_host_list:
        - 2016.animecon.fi
      tracontent_ssl_certificate: /srv/letsencrypt/secrets/animecon.fi/chained.pem
      tracontent_ssl_certificate_key: /srv/letsencrypt/secrets/animecon.fi/domain.key
      tracontent_port: 8005
      tracontent_secret_key: "{{ vault_animecon_tracontent_secret_key }}"
      tracontent_postgresql_username: animecon
      tracontent_postgresql_password: "{{ vault_animecon_tracontent_postgresql_password }}"
      tracontent_postgresql_database: animecon
      tracontent_kompassi_oauth2_client_id: "{{ vault_animecon_tracontent_kompassi_oauth2_client_id }}"
      tracontent_kompassi_oauth2_client_secret: "{{ vault_animecon_tracontent_kompassi_oauth2_client_secret }}"
      tracontent_favicon: null
      tracontent_editor_group_list:
        - animecon-staff

    - role: tracontent
      tags: [tracontent]
      tracontent_hostname: tracontent.aicon.fi
      tracontent_static_dir: /srv/tracontent.aicon.fi/public_html/static
      tracontent_allowed_host_list:
        - aicon.fi
      tracontent_ssl_certificate: /srv/letsencrypt/secrets/aicon.fi/chained.pem
      tracontent_ssl_certificate_key: /srv/letsencrypt/secrets/aicon.fi/domain.key
      tracontent_port: 8006
      tracontent_secret_key: "{{ vault_aicon_tracontent_secret_key }}"
      tracontent_postgresql_username: aicon
      tracontent_postgresql_password: "{{ vault_aicon_tracontent_postgresql_password }}"
      tracontent_postgresql_database: aicon
      tracontent_kompassi_oauth2_client_id: "{{ vault_aicon_tracontent_kompassi_oauth2_client_id }}"
      tracontent_kompassi_oauth2_client_secret: "{{ vault_aicon_tracontent_kompassi_oauth2_client_secret }}"
      tracontent_favicon: null
      tracontent_editor_group_list:
        - aicon-staff

    - role: kirppu
      tags: [kirppu]

    - role: static
      tags: [static]
      static_hostname: 2007.tracon.fi

    - role: static
      tags: [static]
      static_hostname: 2009.tracon.fi

    - role: static
      tags: [static]
      static_hostname: 2010.tracon.fi

    - role: static
      tags: [static]
      static_hostname: 2011.tracon.fi

    - role: static
      tags: [static]
      static_hostname: 2012.tracon.fi

    - role: static
      tags: [static]
      static_hostname: 2013.tracon.fi

    - role: static
      tags: [static]
      static_hostname: 2014.tracon.fi

    - role: static
      tags: [static]
      static_hostname: 2015.tracon.fi

    - role: static
      tags: [static]
      static_hostname: media.tracon.fi


    - role: infokala
      tags: [infokala]
    - role: infotv
      tags: [infotv]
    - role: edegal
      tags: [edegal]

    - role: oidentd
      tags: [oidentd]
    - role: slackirc
      tags: [slackirc]

    - role: letsencrypt
      tags: [letsencrypt]
      letsencrypt_domains:
        # ugly
        - name: tracon.fi
          subject_alt_name: "DNS:tracon.fi,DNS:www.tracon.fi,DNS:nuoli.tracon.fi,DNS:2016.tracon.fi,DNS:2017.tracon.fi,DNS:blog.tracon.fi,DNS:r.tracon.fi,DNS:2007.tracon.fi,DNS:2009.tracon.fi,DNS:2010.tracon.fi,DNS:2011.tracon.fi,DNS:2012.tracon.fi,DNS:2013.tracon.fi,DNS:2014.tracon.fi,DNS:2015.tracon.fi,DNS:media.tracon.fi,DNS:kulukorvaus.tracon.fi,DNS:kirppu.tracon.fi"
        - name: hitpoint.tracon.fi
          subject_alt_name: "DNS:hitpoint.tracon.fi,DNS:www.hitpoint.tracon.fi,DNS:2015.hitpoint.tracon.fi,DNS:2016.hitpoint.tracon.fi,DNS:2017.hitpoint.tracon.fi,DNS:kulukorvaus.hitpoint.tracon.fi"
        - name: ry.tracon.fi
          subject_alt_name: "DNS:ry.tracon.fi,DNS:kulukorvaus.ry.tracon.fi"

        # TODO näillä mitään syytä olla omina varmenteinaan? ehkä siirretään osaks tracon.fi varmennetta
        - name: infotv.tracon.fi
          subject_alt_name: "DNS:infotv.tracon.fi,DNS:info-tv.tracon.fi"
        - name: infokala.tracon.fi
          subject_alt_name: "DNS:infokala.tracon.fi,DNS:infoloki.tracon.fi"

        - name: animecon.fi
          subject_alt_name: "DNS:animecon.fi,DNS:www.animecon.fi,DNS:2016.animecon.fi"
        - name: aicon.fi
          subject_alt_name: "DNS:aicon.fi,DNS:www.aicon.fi,DNS:2016.aicon.fi,DNS:m.aicon.fi"
        - name: conikuvat.fi
          subject_alt_name: "DNS:beta.conikuvat.fi"

- hosts: kompassi-servers
  gather_facts: no
  roles:
    # default site
    - role: redirect
      tags: [redirect]
      redirect_hostname: "{{ inventory_hostname }}"
      redirect_allowed_hosts: "{{ inventory_hostname }} www.{{ inventory_hostname }}"
      redirect_target: https://kompassi.eu
      redirect_ssl: true
      redirect_default: true

    - role: postgresql-docker
      tags: [postgresql-docker]
      postgresql_hostname: kompassi.eu
      postgresql_username: kompassi
      postgresql_password: "{{ kompassi_postgresql_password }}"
      postgresql_database: kompassi

    - role: kompassi
      tags: [kompassi]
    - role: atlasso
      tags: [atlasso]
    - role: shoottikala
      tags: [shoottikala]

    - role: letsencrypt
      tags: [letsencrypt]
      letsencrypt_domains:
        - name: kompassi.eu
          subject_alt_name: "DNS:kompassi.eu,DNS:www.kompassi.eu,DNS:neula.kompassi.eu"
        - name: atlasso.tracon.fi
          subject_alt_name: "DNS:atlasso.tracon.fi"
        - name: photoshoot.conikuvat.fi
          subject_alt_name: "DNS:photoshoot.conikuvat.fi"

- hosts: management-servers
  gather_facts: no
  roles:
    - role: jenkins
      tags: [jenkins]
      jenkins_ssl_certificate: /srv/letsencrypt/secrets/monokkeli.tracon.fi/chained.pem
      jenkins_ssl_certificate_key: /srv/letsencrypt/secrets/monokkeli.tracon.fi/domain.key

    - role: postgresql-docker
      tags: [postgresql-docker]
      postgresql_hostname: jenkins.tracon.fi
      postgresql_username: jenkinslave
      postgresql_password: "{{ jenkinslave_postgresql_password }}"
      postgresql_database: test_kompassi

    - role: jenkinslave
      tags: [jenkinslave]

    - role: prometheus
      tags: [prometheus]

    # get SSL for future service
    - role: redirect
      tags: [redirect]
      redirect_hostname: kibana.tracon.fi
      redirect_allowed_hosts: kibana.tracon.fi
      redirect_target: https://tracon.fi
      redirect_ssl: false
      redirect_letsencrypt: true

    - role: letsencrypt
      tags: [letsencrypt]
      letsencrypt_domains:
        - name: monokkeli.tracon.fi
          subject_alt_name: "DNS:jenkins.tracon.fi,DNS:kibana.tracon.fi,DNS:grafana.tracon.fi,DNS:prometheus.tracon.fi,DNS:alertmanager.tracon.fi"


- hosts: hop-servers
  gather_facts: no
  roles:
    - role: base
      tags: [base]
      nameservers:
        - 8.8.8.8
        - 8.8.4.4

    - role: node-exporter
      tags: [node-exporter]

    - role: prebackup
      tags: [prebackup]

    - role: nginx
      tags: [nginx]

    - role: redirect
      tags: [redirect]
      redirect_hostname: "{{ inventory_hostname }}"
      redirect_allowed_hosts: "{{ inventory_hostname }} www.{{ inventory_hostname }}"
      redirect_target: https://kompassi.eu
      redirect_default: true
      redirect_ssl_certificate: /srv/letsencrypt/secrets/putki.tracon.fi/chained.pem
      redirect_ssl_certificate_key: /srv/letsencrypt/secrets/putki.tracon.fi/domain.key

    - role: proxy
      tags: [proxy]
      proxy_hostname: vara.kompassi.eu

      # nuoli.kompassi.eu
      proxy_target: https://91.105.251.77

      proxy_ssl_certificate: /srv/letsencrypt/secrets/vara.kompassi.eu/chained.pem
      proxy_ssl_certificate_key: /srv/letsencrypt/secrets/vara.kompassi.eu/domain.key

    - role: letsencrypt
      tags: [letsencrypt]
      letsencrypt_domains:
        - name: putki.tracon.fi
          subject_alt_name: "DNS:putki.tracon.fi"
        - name: vara.kompassi.eu
          subject_alt_name: "DNS:vara.kompassi.eu"
