- name: "Update edegal docker image from the registry"
  docker_image:
    name: "{{ edegal_image }}"
    force: yes
  tags: [edegal-deploy]

- name: "Create {{ edegal_hostname }}-rabbitmq container"
  docker_container:
    name: "{{ edegal_hostname }}-rabbitmq"
    restart_policy: unless-stopped
    image: rabbitmq
    volumes:
      - "{{ edegal_hostname }}-rabbitmq-data:/var/lib/rabbitmq"
    env:
      RABBITMQ_ERLANG_COOKIE: "{{ edegal_rabbitmq_cookie }}"
      RABBITMQ_DEFAULT_USER: "{{ edegal_rabbitmq_username }}"
      RABBITMQ_DEFAULT_PASS: "{{ edegal_rabbitmq_password }}"
      RABBITMQ_DEFAULT_VHOST: "{{ edegal_rabbitmq_vhost }}"

- name: "Create {{ edegal_hostname }}-memcache container"
  docker_container:
    name: "{{ edegal_hostname }}-memcache"
    image: memcached
    restart_policy: unless-stopped

- name: "Create {{ edegal_hostname }}-gunicorn container"
  docker_container:
    name: "{{ edegal_hostname }}-gunicorn"
    image: "{{ edegal_image }}"
    env_file: /srv/{{ edegal_hostname }}/env
    recreate: yes
    restart_policy: unless-stopped
    command: "gunicorn --bind=0.0.0.0:8000 --workers={{ edegal_workers }} --timeout={{ edegal_timeout }} edegal_site.wsgi:application"
    ports:
      - "127.0.0.1:{{ edegal_port }}:8000"
    volumes:
      - /mnt/coppermine_albums:/usr/src/app/media/coppermine_albums
      - /mnt/coppermine_albums/pictures:/usr/src/app/media/pictures
      - /mnt/coppermine_albums/previews:/usr/src/app/media/previews
    links:
      - "{{ edegal_hostname }}-rabbitmq:rabbitmq"
      - "{{ edegal_postgresql_container }}:postgres"
      - "{{ edegal_hostname }}-memcache:memcache"
  tags: [edegal-deploy]

- name: "Create {{ edegal_hostname }}-celery container"
  docker_container:
    name: "{{ edegal_hostname }}-celery"
    image: "{{ edegal_image }}"
    restart_policy: unless-stopped
    command: "celery -A edegal_site.celery:app worker"
    env_file: /srv/{{ edegal_hostname }}/env
    recreate: yes
    volumes:
      - /mnt/coppermine_albums:/usr/src/app/media/coppermine_albums
      - /mnt/coppermine_albums/pictures:/usr/src/app/media/pictures
      - /mnt/coppermine_albums/previews:/usr/src/app/media/previews
    links:
      - "{{ edegal_hostname }}-rabbitmq:rabbitmq"
      - "{{ edegal_postgresql_container }}:postgres"
      - "{{ edegal_hostname }}-memcache:memcache"
  tags: [edegal-deploy]

# PROBLEMS:
# - rsync not installed inside container, apt-get install rsync fails
# - cleanup parameter added in ansible 2.2 (not yet released at the time of writing)

# - name: "Extract static files from inside container (docker_container version)"
#   docker_container:
#     name: "{{ edegal_hostname }}-extract-static"
#     cleanup: yes
#     detach: no
#     image: "{{ edegal_image }}"
#     command: "rsync -aqH --delete-after /usr/src/app/static /tmp/edegal-static-files/"
#     volumes:
#       - "/tmp/edegal-static-files:/srv/{{ edegal_hostname }}/public_html"

# PROBLEMS:
# - does not remove stale files
- name: "Extract static files from inside container (command version)"
  command: >
    /usr/bin/docker cp {{ edegal_hostname }}-gunicorn:/usr/src/app/static /srv/{{ edegal_hostname }}/public_html/
  tags: [edegal-deploy]
