- name: "Create {{ edegal_user }} group to facilitate access to static files"
  group:
    name: "{{ edegal_user }}"
    system: yes

    # XXX specific
    gid: "{{ edegal_uid }}"

- name: "Create {{ edegal_user }} user"
  user:
    name: "{{ edegal_user }}"
    group: "{{ edegal_user }}"
    uid: "{{ edegal_uid }}"
    groups: "{{ edegal_extra_groups }}"

- name: "Add the nginx user to the {{ edegal_user }} group"
  user:
    name: nginx
    groups: "{{ edegal_user }}"
    append: yes

- name: "Create host data directory"
  file:
    path: /srv/{{ edegal_hostname }}
    state: directory
    owner: root
    group: "{{ edegal_user }}"
    mode: 02710

- name: "Create static files directory"
  file:
    path: /srv/{{ edegal_hostname }}/public_html
    state: directory
    owner: root
    group: "{{ edegal_user }}"
    mode: 02750

- name: "Create env file"
  template:
    src: "edegal.env.j2"
    dest: /srv/{{ edegal_hostname }}/env
    mode: 0600
  tags: [edegal-deploy]

- name: "Setup nginx vhost for {{ edegal_hostname }}"
  template:
    src: edegal.nginx.j2
    dest: /etc/nginx/sites-available/{{ edegal_hostname }}
    mode: 0644
  notify: restart nginx
  tags: [edegal-nginx]

- name: "Enable nginx vhost for {{ edegal_hostname }}"
  file:
      src: /etc/nginx/sites-available/{{ edegal_hostname }}
      path: /etc/nginx/sites-enabled/{{ edegal_hostname }}
      state: link
  notify: restart nginx
  tags: [edegal-nginx]
