- name: "Setup nginx vhost for {{ tracontent_alias_hostname }}"
  template:
    src: tracontentalias.nginx.j2
    dest: /etc/nginx/sites-available/{{ tracontent_alias_hostname }}
    mode: 0644
  notify: restart nginx

- name: "Enable nginx vhost for {{ tracontent_alias_hostname }}"
  file:
    src: /etc/nginx/sites-available/{{ tracontent_alias_hostname }}
    path: /etc/nginx/sites-enabled/{{ tracontent_alias_hostname }}
    state: link
  notify: restart nginx
