- name: install packages
  apt: name={{item}} state=present
  notify: restart oidentd
  become: true
  with_items:
    - oidentd

- name: configure oidentd
  copy: src=oidentd.conf dest=/etc/oidentd.conf
  become: true
  notify: restart oidentd

- name: allow oidentd through the firewall
  ufw: rule=allow port=113 proto=tcp
