version: '3'

services:
  db:
    restart: always
    # Latest supported by Confluence is Postgres 10
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /opt/atlassian/db:/var/lib/postgresql/data

  crowd:
    restart: always
    image: atlassian/crowd
    ports:
      - 8095:8095
    environment:
      - ATL_PROXY_NAME=crowd.tracon.fi
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_SCHEME=https
      - ATL_TOMCAT_SECURE=true
    volumes:
      - /opt/atlassian/crowd-home:/var/atlassian/application-data/crowd

  confluence:
    restart: always
    image: tracon-confluence
    ports:
      - 8090:8090
      - 8091:8091
    environment:
      - JVM_MINIMUM_MEMORY=2048m
      - JVM_MAXIMUM_MEMORY=2048m
      - ATL_PROXY_NAME=confluence.tracon.fi
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_SCHEME=https
      - ATL_TOMCAT_SECURE=true
    volumes:
      - /opt/atlassian/confluence-home:/var/atlassian/application-data/confluence

  jira:
    restart: always
    image: tracon-jira
    ports:
      - 8080:8080
    environment:
      - JVM_MINIMUM_MEMORY=384m
      - JVM_MAXIMUM_MEMORY=1300m
      - ATL_PROXY_NAME=jira.tracon.fi
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_SCHEME=https
      - ATL_TOMCAT_SECURE=true
    volumes:
      - /opt/atlassian/jira-home:/var/atlassian/application-data/jira
