- name: create local admin users
  user:
    append: yes
    groups: sudo
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    shell: /bin/bash
  with_items: "{{ base_admin_users }}"
  tags:
    - admins

- name: set local admin private keys
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.key }}"
  tags:
    - admins
  with_items: "{{ base_authorized_keys }}"

- name: remove obsolete local admin private keys
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.key }}"
    state: absent
  tags:
    - admins
  with_items: "{{ base_authorized_keys_to_remove }}"
