- name: Install oidentd
  apt: name=oidentd state=present
  notify: restart oidentd

- name: Configure oidentd
  copy: src=oidentd.conf dest=/etc/oidentd.conf
  notify: restart oidentd

- name: Allow oidentd through the firewall
  ufw: rule=allow port=113 proto=tcp

- name: "Create slackirc group to facilitate access to static files"
  group: name=slackirc system=yes

- name: "Create host data directory"
  file: path=/srv/slackirc state=directory owner=root group=slackirc mode=02710

- name: Install configuration file
  copy:
    content: "{{ slackirc_config|to_nice_json }}"
    dest: /srv/slackirc/slackirc.json
    owner: root
    group: slackirc

- name: Create slackirc container
  when: "{{ slackirc_enabled }}"
  docker_container:
    name: slackirc
    image: tracon/slackirc
    restart_policy: unless-stopped
    volumes:
      - /srv/slackirc/slackirc.json:/slackirc.json:ro

- name: Install daily restart script
  when: "{{ slackirc_enabled }}"
  copy: src=slackirc.crondaily.sh dest=/etc/cron.daily/slackirc mode=0755
