- name: "Create slackirc group to facilitate access to static files"
  group: name=slackirc system=yes

- name: "Create host data directory"
  file: path=/srv/slackirc state=directory owner=root group=slackirc mode=02710

- name: Install configuration file
  copy:
    content: "{{ slackirc_config|to_nice_json }}"
    dest: /srv/slackirc/slackirc.json
    owner: root
    group: slackirc

- name: "Update slackirc docker image from the registry"
  docker_image:
    name: "{{ slackirc_image }}"
    force: yes

- name: Create slackirc container
  when: "{{ slackirc_enabled }}"
  docker_container:
    name: slackirc
    image: "{{ slackirc_image }}"
    restart_policy: unless-stopped
    recreate: true
    volumes:
      - /srv/slackirc/slackirc.json:/slackirc.json:ro
    # env:
    #   NODE_ENV: development

- name: Install daily restart script
  when: "{{ slackirc_enabled }}"
  copy: src=slackirc.crondaily.sh dest=/etc/cron.daily/slackirc mode=0755
