- name: add java apt repository
  apt_repository: repo='ppa:webupd8team/java' update-cache=yes

- name: accept oracle java license
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  changed_when: false

- name: install oracle java
  apt: pkg=oracle-java8-installer state=latest
