- name: "Setup nginx vhost for {{ atlasso_hostname }}"
  template: src=atlasso.nginx.j2 dest=/etc/nginx/sites-available/{{ atlasso_hostname }} mode=0644
  notify: restart nginx
  tags: [atlasso-nginx]

- name: "Enable nginx vhost for {{ atlasso_hostname }}"
  file: >
    src=/etc/nginx/sites-available/{{ atlasso_hostname }}
    path=/etc/nginx/sites-enabled/{{ atlasso_hostname }}
    state=link
  notify: restart nginx
  tags: [atlasso-nginx]

- name: "Update Atlasso docker image from the registry"
  docker_image:
    name: tracon/atlasso
    force: yes
  tags: [atlasso-deploy]

- name: "Create Atlasso container for {{ atlasso_hostname }}"
  docker_container:
    name: "{{ atlasso_hostname }}"
    image: tracon/atlasso
    recreate: yes
    command: "gunicorn --bind=0.0.0.0:8000 --workers={{ atlasso_workers }} atlasso.wsgi:application"
    ports:
      - "{{ atlasso_port }}:8000"
    links:
      - "{{ atlasso_postgresql_container }}:postgres"
    env:
      ADMINS: "{{ atlasso_admins }}"
      ALLOWED_HOSTS: "{{ atlasso_allowed_hosts }}"
      DATABASE_URL: "postgres://{{ atlasso_postgresql_username }}:{{ atlasso_postgresql_password }}@postgres/{{ atlasso_postgresql_database }}"
      DEFAULT_FROM_EMAIL: "{{ atlasso_default_from_email }}"
      EMAIL_HOST: "{{ atlasso_email_host }}"
      KOMPASSI_CROWD_APPLICATION_NAME: "{{ atlasso_crowd_application_name }}"
      KOMPASSI_CROWD_APPLICATION_PASSWORD: "{{ atlasso_crowd_application_password }}"
      KOMPASSI_OAUTH2_CLIENT_ID: "{{ atlasso_kompassi_oauth2_client_id }}"
      KOMPASSI_OAUTH2_CLIENT_SECRET: "{{ atlasso_kompassi_oauth2_client_secret }}"
      SECRET_KEY: "{{ atlasso_secret_key }}"
  tags: [atlasso-deploy]
