edegal_image: conikuvat/edegal
edegal_hostname: conikuvat.fi
edegal_port: 8009
edegal_ssl: true
edegal_letsencrypt: true
edegal_user: conikuvat

# hardcoded due to youzen.b2.fi NFS
edegal_uid: 1082
edegal_extra_groups: users

# old Geotrust RapidSSL certificate
# edegal_ssl_certificate: /etc/ssl/certs/edegal.eu+intermediate.crt
# edegal_ssl_certificate_key: /etc/ssl/private/edegal.eu.key

# new LetsEncrypt certificates
edegal_ssl_certificate: /srv/letsencrypt/secrets/conikuvat.fi/chained.pem
edegal_ssl_certificate_key: /srv/letsencrypt/secrets/conikuvat.fi/domain.key

edegal_allowed_hosts: "{{ edegal_hostname }}"
edegal_default_from_email: yhteys@conikuvat.fi
edegal_email_host: sr0a.pahaip.fi
edegal_cache_url: memcache://memcache
edegal_admins: "Santtu Pajukanta <santtu@pajukanta.fi>"
edegal_rabbitmq_username: conikuvat
edegal_rabbitmq_vhost: conikuvat
edegal_postgresql_hostname: siilo.tracon.fi
edegal_postgresql_username: conikuvat
edegal_postgresql_database: conikuvat
edegal_workers: 8
edegal_timeout: 60

# coppermine import
edegal_coppermine_mysql_host: kirito.b2.fi
edegal_coppermine_mysql_username: b2_coppermine
edegal_coppermine_mysql_database: b2_coppermine

# FIXME ugly. but we'll move to kubernetes anyway soon.
edegal_volumes:
  - /mnt/coppermine_albums:/usr/src/app/media/coppermine_albums
  - /mnt/coppermine_albums/pictures:/usr/src/app/media/pictures
  - /mnt/coppermine_albums/previews:/usr/src/app/media/previews
  - /mnt/coppermine_albums/uploads:/usr/src/app/media/uploads

edegal_media_nginx_fragment: |
    # both conikuvat and larppikuvat use the same static files here!
    location /static/ {
        alias /srv/conikuvat.fi/public_html/static/;
        expires 30m;
    }

    location /media/coppermine_albums/ {
        alias /mnt/coppermine_albums/;
        expires 30m;
    }

    location /media/pictures/ {
        alias /mnt/coppermine_albums/pictures/;
        expires 30m;
    }

    location /media/previews/ {
        alias /mnt/coppermine_albums/previews/;
        expires 30m;
    }

    location /media/uploads/ {
        alias /mnt/coppermine_albums/uploads/;
        expires 30m;
    }

    location /media/ {
        return 404;
    }
