infokala_secret_key: "{{ vault_infokala_secret_key }}"
infokala_kompassi_oauth2_client_id: "{{ vault_infokala_kompassi_oauth2_client_id }}"
infokala_kompassi_oauth2_client_secret: "{{ vault_infokala_kompassi_oauth2_client_secret }}"
infokala_postgresql_password: "{{ vault_infokala_postgresql_password }}"

infotv_secret_key: "{{ vault_infotv_secret_key }}"
infotv_kompassi_oauth2_client_id: "{{ vault_infotv_kompassi_oauth2_client_id }}"
infotv_kompassi_oauth2_client_secret: "{{ vault_infotv_kompassi_oauth2_client_secret }}"
infotv_postgresql_password: "{{ vault_infotv_postgresql_password }}"

tracontent_secret_key: "{{ vault_tracontent_secret_key }}"
tracontent_kompassi_oauth2_client_id: "{{ vault_tracontent_kompassi_oauth2_client_id }}"
tracontent_kompassi_oauth2_client_secret: "{{ vault_tracontent_kompassi_oauth2_client_secret }}"
tracontent_postgresql_password: "{{ vault_tracontent_postgresql_password }}"

kirppu_secret_key: "{{ vault_kirppu_secret_key }}"
kirppu_kompassi_oauth2_client_id: "{{ vault_kirppu_kompassi_oauth2_client_id }}"
kirppu_kompassi_oauth2_client_secret: "{{ vault_kirppu_kompassi_oauth2_client_secret }}"
kirppu_postgresql_password: "{{ vault_kirppu_postgresql_password }}"
kirppu_kompassi_api_v1_name: "{{ vault_kirppu_kompassi_api_v1_name }}"
kirppu_kompassi_api_v1_password: "{{ vault_kirppu_kompassi_api_v1_password }}"

edegal_secret_key: "{{ vault_edegal_secret_key }}"
edegal_postgresql_password: "{{ vault_edegal_postgresql_password }}"
edegal_rabbitmq_cookie: "{{ vault_edegal_rabbitmq_cookie }}"
edegal_rabbitmq_password: "{{ vault_edegal_rabbitmq_password }}"
edegal_coppermine_mysql_password: "{{ vault_edegal_coppermine_mysql_password }}"
edegal_kompassi_oauth2_client_id: "{{ vault_edegal_kompassi_oauth2_client_id }}"
edegal_kompassi_oauth2_client_secret: "{{ vault_edegal_kompassi_oauth2_client_secret }}"

redmine_postgresql_password: "{{ vault_redmine_postgresql_password }}"
