- name: "Create {{ postgresql_hostname }}-postgres container"
  docker_container:
    name: "{{ postgresql_hostname }}-postgres"
    image: postgres
    env:
      POSTGRES_USER: "{{ postgresql_username }}"
      POSTGRES_PASSWORD: "{{ postgresql_password }}"
      POSTGRES_DB: "{{ postgresql_database }}"
    volumes:
      - "{{ postgresql_hostname }}-postgres-data:/var/lib/postgresql/data"
