- name: "Create {{ postgresql_hostname }}-postgres container"
  docker_container:
    name: "{{ postgresql_hostname }}-postgres"
    image: postgres
    restart_policy: unless-stopped
    env:
      POSTGRES_USER: "{{ postgresql_username }}"
      POSTGRES_PASSWORD: "{{ postgresql_password }}"
      POSTGRES_DB: "{{ postgresql_database }}"
    volumes:
      - "{{ postgresql_hostname }}-postgres-data:/var/lib/postgresql/data"

- name: Make sure backup directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/backups
    - /var/backups/postgresql

- name: Set up pre-backup script
  template:
    src: pre-backup.sh.j2
    dest: /etc/pre-backup.d/{{ postgresql_hostname }}-postgres.sh
    mode: 0755
