# install actions-runner-controller using helm with
# helm repo add actions-runner-controller https://summerwind.github.io/actions-runner-controller
# kubectl create namespace actions-runner-system
# helm install -n actions-runner-system actions-runner-controller actions-runner-controller/actions-runner-controller

# then deploy these resources

apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: con2
spec:
  replicas: 2
  template:
    spec:
      organization: con2
      image: summerwind/actions-runner-dind
      dockerdWithinRunnerContainer: true
      serviceAccountName: actions-runner
      automountServiceAccountToken: true
      volumeMounts:
       - mountPath: /runner
         name: runner
      volumes:
       - emptyDir: {}
         name: runner      

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-runner

---
# NOTE: this policy is still WIP, we're not even there yet
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: actions-runner
rules:
- apiGroups: ["", "apps", "networking.k8s.io", "extensions"] # "" indicates the core API group
  resources: ["deployments", "services", "configmaps", "secrets", "ingresses", "persistentvolumeclaims"]
  verbs: ["get", "watch", "list", "patch", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: actions-runner
subjects:
- kind: ServiceAccount
  name: actions-runner
  namespace: actions-runner-system
roleRef:
  kind: ClusterRole
  name: actions-runner
  apiGroup: rbac.authorization.k8s.io