grafana:
  enabled: true

prometheus:
  enabled: true

prometheus:
  alertmanager:
    persistentVolume:
      enabled: false

prometheus:
  server:
    persistentVolume:
      enabled: false

loki:
  persistence:
    enabled: true
    storageClassName: longhorn
    size: 10Gi
