image:
  repository: redis
  tag: 6.0.8-buster

redis:
  # must match ^[\\w-\\.]+$) and can be templated
  masterGroupName: "qb-redis-ha"

haproxy:
  enabled: true
  timeout:
    # redis default timeout is "about 5 minutes" so make this longer
    # NOTE: these are milliseconds if no unit is provided :)))
    client: 330s
    server: 330s

exporter:
  enabled: true

persistentVolume:
  enabled: true
  storageClass: local-path
  accessModes:
    - ReadWriteOnce
  size: 10Gi
