# https://github.com/bitnami/charts/tree/master/bitnami/redmine/

# required for upgrade
# kubectl get secret --namespace redmine redmine -o jsonpath="{.data.redmine-password}" | base64 --decode
redminePassword: redacted

databaseType: postgresql
mariadb:
  enabled: false

externalDatabase:
  host: siilo.tracon.fi
  name: redmine
  user: redmine
  password: redacted
  port: 5432

ingress:
  enabled: true
  certManager: true
  tls: true
  hostname: pora.tracon.fi
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

persistence:
  storageClass: longhorn-nfs
  accessModes:
    - ReadWriteMany

service:
  type: ClusterIP
