user:
  create: true
  email: root@tracon.fi
  password: redacted

nginx:
  enabled: false

ingress:
  enabled: true
  hostname: sentry.con2.fi

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

  tls:
    - secretName: sentry-letsencrypt
      hosts:
        - sentry.con2.fi

filestore:
  filesystem:
    persistence:
      storageClass: longhorn-nfs
      persistentWorkers: true

postgresql:
  enabled: false

externalPostgresql:
  host: siilo.tracon.fi
  username: sentry
  password: redacted

rabbitmq:
  enabled: false

metrics:
  enabled: true

redis:
  enabled: false

externalRedis:
  host: redis-ha-haproxy.redis-ha.svc.cluster.local
