# Set up Kompassi for being backed up by an external backup system.
# It is assumed to
# 1. execute /usr/local/sbin/pre-backup
# 2. backup whatever lies under /etc /srv /var/backups

# TODO make a pre-backup.d system to support split pre-backup scripts

- name: Set up pre-backup script
  copy: src=pre-backup.sh dest=/usr/local/sbin/pre-backup mode=0755

- name: Make sure backup directories exist
  file: path={{ item }} state=directory
  with_items:
    - /var/backups
    - /var/backups/postgresql
