- name: "Update Kompassi docker images from the registry"
  docker_image:
    name: "{{ item }}"
    force: yes
  with_items:
    - tracon/kompassi-gunicorn
    - tracon/kompassi-celery
  tags: [kompassi-deploy]

- name: "Create {{ kompassi_hostname }}-postgres container"
  docker_container:
    name: "{{ kompassi_hostname }}-postgres"
    image: postgres
    env:
      POSTGRES_USER: "{{ kompassi_postgresql_username }}"
      POSTGRES_PASSWORD: "{{ kompassi_postgresql_password }}"
      POSTGRES_DB: "{{ kompassi_postgresql_database }}"
    volumes:
      - "{{ kompassi_hostname }}-postgres-data:/var/lib/postgresql/data"
  tags: [kompassi-deploy]

- name: "Create {{ kompassi_hostname }}-rabbitmq container"
  docker_container:
    name: "{{ kompassi_hostname }}-rabbitmq"
    image: rabbitmq
    env:
      RABBITMQ_ERLANG_COOKIE: "{{ kompassi_rabbitmq_cookie }}"
      RABBITMQ_DEFAULT_USER: "{{ kompassi_rabbitmq_username }}"
      RABBITMQ_DEFAULT_PASS: "{{ kompassi_rabbitmq_password }}"
      RABBITMQ_DEFAULT_VHOST: "{{ kompassi_rabbitmq_vhost }}"
  tags: [kompassi-deploy]

- name: "Create {{ kompassi_hostname }}-memcache container"
  docker_container:
    name: "{{ kompassi_hostname }}-memcache"
    image: memcached
  tags: [kompassi-deploy]

- name: "Create {{ kompassi_hostname }}-gunicorn container"
  docker_container:
    name: "{{ kompassi_hostname }}-gunicorn"
    image: tracon/kompassi-gunicorn
    env_file: /srv/{{ kompassi_hostname }}/env
    recreate: yes
    command: "gunicorn --bind=0.0.0.0:8000 --workers={{ kompassi_workers }} turska.wsgi:application"
    ports:
      - "{{ kompassi_port }}:8000"
    links:
      - "{{ kompassi_hostname }}-rabbitmq:rabbitmq"
      - "{{ kompassi_hostname }}-postgres:postgres"
      - "{{ kompassi_hostname }}-memcache:memcache"
  tags: [kompassi-deploy]

- name: "Create {{ kompassi_hostname }}-celery container"
  docker_container:
    name: "{{ kompassi_hostname }}-celery"
    image: tracon/kompassi-celery
    env_file: /srv/{{ kompassi_hostname }}/env
    recreate: yes
    links:
      - "{{ kompassi_hostname }}-rabbitmq:rabbitmq"
      - "{{ kompassi_hostname }}-postgres:postgres"
      - "{{ kompassi_hostname }}-memcache:memcache"
  tags: [kompassi-deploy]

# PROBLEMS:
# - rsync not installed inside container, apt-get install rsync fails
# - cleanup parameter added in ansible 2.2 (not yet released at the time of writing)

# - name: "Extract static files from inside container (docker_container version)"
#   docker_container:
#     name: "{{ kompassi_hostname }}-extract-static"
#     cleanup: yes
#     detach: no
#     image: tracon/kompassi-gunicorn
#     command: "rsync -aqH --delete-after /usr/src/app/static /tmp/kompassi-static-files/"
#     volumes:
#       - "/tmp/kompassi-static-files:/srv/{{ kompassi_hostname }}/public_html"

# PROBLEMS:
# - does not remove stale files
- name: "Extract static files from inside container (command version)"
  command: >
    /usr/bin/docker cp {{ kompassi_hostname }}-gunicorn:/usr/src/app/static /srv/{{ kompassi_hostname }}/public_html/
  tags: [kompassi-deploy]
