- name: "Create host data directory"
  file: path=/srv/{{ kompassi_hostname }} state=directory owner=root group=www-data mode=0710

- name: "Create env file"
  template: src=env.j2 dest=/srv/{{ kompassi_hostname }}/env mode=0600

- name: "Create {{ kompassi_hostname }}-postgres container"
  docker_container:
    name: "{{ kompassi_hostname }}-postgres"
    image: postgres
    volumes:
      - "{{ kompassi_hostname }}-postgres-data:/var/lib/postgresql/data"

- name: "Create {{ kompassi_hostname }}-rabbitmq container"
  docker_container:
    name: "{{ kompassi_hostname }}-rabbitmq"
    image: rabbitmq

- name: "Create {{ kompassi_hostname }}-memcache container"
  docker_container:
    name: "{{ kompassi_hostname }}-memcache"
    image: memcached

- name: "Create {{ kompassi_hostname }}-gunicorn container"
  docker_container:
    name: "{{ kompassi_hostname }}-gunicorn"
    image: tracon/kompassi-gunicorn
    env_file: /srv/{{ kompassi_hostname }}/env
    ports:
      - 8000:8000
    links:
      - "{{ kompassi_hostname }}-rabbitmq:rabbitmq"
      - "{{ kompassi_hostname }}-postgres:postgres"
      - "{{ kompassi_hostname }}-memcache:memcache"

- name: "Create {{ kompassi_hostname }}-celery container"
  docker_container:
    name: "{{ kompassi_hostname }}-celery"
    image: tracon/kompassi-celery
    env_file: /srv/{{ kompassi_hostname }}/env
    links:
      - "{{ kompassi_hostname }}-rabbitmq:rabbitmq"
      - "{{ kompassi_hostname }}-postgres:postgres"
      - "{{ kompassi_hostname }}-memcache:memcache"
