- name: "Create {{ kompassi_user }} group to facilitate access to static files"
  group: name={{ kompassi_user }} system=yes gid={{ kompassi_gid }}

- name: "Create {{ kompassi_user }} user to facilitate access to static files"
  user: name={{ kompassi_user }} system=yes uid={{ kompassi_uid }} group={{ kompassi_user }}

- name: "Add the nginx user to the kompassi group"
  user: name=nginx groups={{ kompassi_user }} append=yes

- name: "Create host data directory"
  file: path=/srv/{{ kompassi_hostname }} state=directory owner=root group={{ kompassi_user }} mode=02710

- name: "Create static files directory"
  file: path=/srv/{{ kompassi_hostname }}/public_html state=directory owner=root group={{ kompassi_user }} mode=02750

- name: "Create upload directory"
  file: path=/srv/{{ kompassi_hostname }}/public_html/media state=directory owner=root group={{ kompassi_user }} mode=02770

- name: "Create env file"
  template: src=kompassi.env.j2 dest=/srv/{{ kompassi_hostname }}/env mode=0600
  tags: [kompassi-deploy]

- name: "Setup nginx vhost for {{ kompassi_hostname }}"
  template: src=kompassi.nginx.j2 dest=/etc/nginx/sites-available/{{ kompassi_hostname }} mode=0644
  notify: restart nginx
  tags: [kompassi-nginx]

- name: "Enable nginx vhost for {{ kompassi_hostname }}"
  file: >
    src=/etc/nginx/sites-available/{{ kompassi_hostname }}
    path=/etc/nginx/sites-enabled/{{ kompassi_hostname }}
    state=link
  notify: restart nginx
  tags: [kompassi-nginx]
