- name: "create nginx vhost for {{ alertmanager_hostname }}"
  template:
    src: alertmanager.nginx.j2
    dest: /etc/nginx/sites-available/{{ alertmanager_hostname }}
    mode: 0644
  notify: restart nginx

- name: "enable nginx vhost for {{ alertmanager_hostname }}"
  file:
    path: /etc/nginx/sites-enabled/{{ alertmanager_hostname }}
    src: /etc/nginx/sites-available/{{ alertmanager_hostname }}
    state: link
  notify: restart nginx

- name: "create htpasswd file for {{ alertmanager_hostname }}"
  copy:
    dest: /etc/nginx/{{ alertmanager_hostname }}.htpasswd
    content: "{{ alertmanager_basic_auth }}"


- name: "create nginx vhost for {{ prometheus_hostname }}"
  template:
    src: prometheus.nginx.j2
    dest: /etc/nginx/sites-available/{{ prometheus_hostname }}
    mode: 0644
  notify: restart nginx

- name: "enable nginx vhost for {{ prometheus_hostname }}"
  file:
    path: /etc/nginx/sites-enabled/{{ prometheus_hostname }}
    src: /etc/nginx/sites-available/{{ prometheus_hostname }}
    state: link
  notify: restart nginx

- name: "create htpasswd file for {{  prometheus_hostname }}"
  copy:
    dest: /etc/nginx/{{ prometheus_hostname }}.htpasswd
    content: "{{ prometheus_basic_auth }}"


- name: "create nginx vhost for {{ grafana_hostname }}"
  template:
    src: grafana.nginx.j2
    dest: /etc/nginx/sites-available/{{ grafana_hostname }}
    mode: 0644
  notify: restart nginx

- name: "enable nginx vhost for {{ grafana_hostname }}"
  file:
    path: /etc/nginx/sites-enabled/{{ grafana_hostname }}
    src: /etc/nginx/sites-available/{{ grafana_hostname }}
    state: link
  notify: restart nginx

