- name: Add docker signing key to APT
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present

- name: Add docker APT repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present update_cache=yes

- name: Install dmsetup (needed on Ubuntu 16.04 Xenial to stop apt-get install docker-engine from hanging indefinitely)
  apt: name=dmsetup state=present

- name: Make device mapper device nodes (see above)
  command: /sbin/dmsetup mknodes
  args:
    creates: /dev/mapper/control

- name: Install Docker Engine and other required packages
  apt: name={{ item }} state=present
  with_items:
    - docker-engine
    - python-docker
    - python-ipaddress

- name: Delete untagged containers, images and volumes every night to save space
  copy:
    src: docker-cleanup.sh
    dest: /etc/cron.daily/docker-cleanup.sh
    owner: root
    group: root
    mode: 0755
