- name: create local admin users
  user: >
    append=yes
    groups=sudo
    name={{ item.username }}
    password={{ item.password }}
    shell=/bin/bash
  with_items: "{{ base_admin_users }}"
  tags:
    - base
    - base-admins

- name: set local admin private keys
  authorized_key: >
    user={{ item.username }}
    key="{{ item.key }}"
  tags:
    - base
    - base-admins
  with_items:
    - username: japsu
      key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDMJa4wePvu27XnXAosnM0vAEfZrrI7K+DwecnCfXPATp3opE59fQLG3c1Kyu/c6j2OIzkMmAkhLb+G7M03XnLY2uU1R5WPAfsOqdamdpyxMEULiSKC0a8dC3mu9tFuidV47ZIHdZjAlUlSkG3ZijLFP4nNEv2viGv47fw1t4mZ1d3XIPOQGeMob7vzHVq9vGByNriiMnwRNNHsYyGco3W3NjW1edYY203gl4220umNN/fXiSGlAZfF7fkMJRodJZBnXqPQdQuE60Cd0sgNJTOQLdlNKRGixf5MjHN+ijMTbxZ0kTff9KRv9sHnk6MGU/eCNmAlk7Hz0aSSC95AJqjQSYOI15GgZtqHpEgCk3VEkCx36PEQD6TJEP1ARS+80tdlUf/mlgLI0NTl6vxSpzIV+MC99e1oRigMipTrZLbGb9oVYFBmKIcWpLb8hEj98zLgdqqpN0Tt8hZLIeVH5Ux13a2Wa6YcINILwBt18sfDR/xcpY9XHZzjeKHDRF8syaWoh/FEvatEqQW2yYnPEuJLfWSj5EzqSAULInRMVUuhPJSntdeFlZDHlzk3y+HH6MeanXB8TQ8StACMgnosw7o4WeNFdhQz+/nmrsp5DuaVl09EP1lDcKytaKso9umresVYNP3ZdJzk8v+V0VtreiOOy854qGaPODjy/H1kKGgjRw== japsu@midna-20180507

    - username: mieleton
      key: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA4NH/ESUc03Q3ls2GpILWtzU3eKLI3fLJhhBlbAxEi9un2oWSN/MLenmMcqmRb7wrsqd9cmGcuW9O3+tca4ppCCMHC65R46Rp0v/G/rNwYGkHv6DNWP7/hrWZesCMiH9XaxBbJlZqay6i3GKoaj7LgtaqozXwq2y/zczPBJ4y2vdM2QgtoU+D1WOwspl4nnkPCwGUjnqQ3JQKJoyDalNVj5tKrS0bLWUD97ugqEDjCYkHjSgGumFPLPio/6fAeSKw1FlBt/ikMYFzdP1/85EhP2jdTjbMIg11NJdUGozgVSn/iBwUqb4ndEcIDV2qauzSxozMHYyx+K8FwFJOLQE9XQ== mieleton@malek
    - username: mieleton
      key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDLBXixHAaQkOpoq1GCeHNEoLyYjuANNoDMU/bJQ9MTlIzhYE7/YKK/6TGcwXMgTY1VwD4c4CHo1IeBhmThXXTwY4iuW+I8SWJvzG9M7i7rfcQISX9BBr71deq7k9qFOUk7WHUO7bQEFt3RupQk40Mvn32mA2bQ4wmAI3N03e7TvXxVGGs8cSt+NbAXerr2gieAr+XVFxqxA/XbAotj0HuDgeRnTZWF8cjViXPBZ/KwM5Nzi102eMC7D8THsxWscjATysa8cQXBlgjUiLhlKH1d9mCIqR9mmwm3fbQnBsHwNKNtyAWr/TQFXFFJNFSFBz4+/q2ZTEoAGND4fR+SlqpWgewzJC7Vm2RLUb4mJDgIuIjmIUHqCgHghxgg4w9ZDGeyJMRMOUAJ0SmtHUmTThpeyz6XUxMosfpQnTvRXd9pcJEniwgOw2AoMfPOo5SwUUWx6oWhx4/M8oRmafEAS+qbH+1kjp4sJonHdUudTVCfMZipoOeTsW/qoyPfhNPcEzoKAUGroDHVCo7aoe1LXkyX9CODwjcxYOtgShEHgjrUnIQK9PHb+Lx9ULjwFh9m/tbhF4ZuWX4kKI2qMKdKSAHpityWlpdPTXINWo3gESS/m/QQVD1GEK1ESo7eW++kkIr3PfXR9epdXqING36to93u9Ju65340AyzcYOyqo1Cr9w== mieleton@korra
    - username: mieleton
      key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDQwPyjJIi9MVE7tuSrseiyJBaNaNxTGMYErfsEeH4+BYGnnYqHjZju0dLbrr2NwGOo+vDztjP+DXR/0osR2s1caQESxmtrL+6I4ai9G2osxmPuq+1JfzZTTPDtPg2PmGOKiNQvkSgkwTHFGpDzG76MPwbZYPWdoXOlmJDvA4OelEuXDXSzmc7uWLnDNbcOjFHE2ng5IJimIPJOEL/4C+Vlcqk31fwy8NOTWzinS18NHrE0ew1JsIxD4rZfmDGQi3Y55kIN16IwXmOiBiRJ2JkKM7ISFiLlQM0wkZcPzDb9wMtAcXAv+5et8zFwtT2Uock3Z7MVrBZnswkEV++VK53yRbnoqjAFgpyS/W5KiK0Sbh/QNHxMdWn1asOxiZW/RDJlPbgdkBxVo8+haNpyGaa+tI4yHlD4hqnp9dL8qSASC6VkiFfWvBtc/Xe3cndOx7fCdVvCHk/lwfyzjCBNAiz9gpaova/KwKwDmXwBKTEJpXv2akJKxEgjtwxyoPQkCxx7VxrCRF3oJjM6I50GHM+YDCG1qgtfICJVo4F0fi+JiOuFIVxaREhkDssVbtx9l7364/tB6DARhAL+6+XmHNtLSJYXwrMLvBFgdfgrr/iRDKnIPsB9hVgROI+kZ87Drle4chrDnYCGwwrAN3rscAl0KOgyU2pRp4onxxbdKxRiMw== mieleton@nerus

    - username: elderx
      key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6nuFlwpu+oLptULErEAG+0zoL7rpAkIuHLCe7vc44Jk2Q4ERQWnlDugUPrctHy3sNcskztr1IncaMY+bdte0blZCj+u+xEVVZ9wOAAWlynZGRd4/ML+QetA/vKjn7ydxbfZ5TBjoBnFngpI7ibf72THe9aZJaSupDz1iF8L2ujKUvvmODrq5CuUYlU1Y5sYd7YQ84FlFqN8UXgtTvOsdB0/NSqo5ibIfR8Zee5oaTkldAYIHEerd0osyxtDL+sopQwTi7qVLJTi5gxGf5UVvQkZP7znzV1dLRwqOUGZ33bTLtj+DUNpp0ek5fW0F6P63Eqrrrkb9XgZwEc0xc8nLZ elderx@mbp

    - username: siikakala
      key: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAIEAnPbG9RKh++Xy32UrmoZStI1qddMXVIU97F5IM460HEptzB8dnXVwvic12Mudq6nk3IBHjBUd6scf6GPRiObm7uQZ8CJWC18HNb7XpQDwXvvkyxiusczE3tfC38PBsqMs7fX2UFhKGfiaGBwm8iKL3BCpZqrfYNBuQV/QyAm3Huc= rsa-key-20091119
    - username: siikakala
      key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCnqoIBlSAFd26E3Wf0Cz9Su2yz/gYJpe0KraZ2nm7CYYvQtmL0hRsNYnAboTogphdQxM2UXZ7HEBmYhyjcgBDKXBBUMhcBJIHhPSuMgwPndHLny568L/idcwP6x04eQqqLYFvLonDuDSSxyF+cWZUHFDMbb+fA/+FmfD/38Bicj3SPoLku9lmXVNJ1Wzfv0fFL6j8o0ivhFC27rWT0eTiHgIzfljqsq7V4tT9vH142b3dawwGRoY566YpchhiyMp+gYTGDrGAUQsiEtejI7xEYayqzjFxFaxQUHRa+FIDYhOcXyEXZRdQu324w8qlJW/lFzzluFW9OgDRmSpVx4rQt siika@hirano
    - username: siikakala
      key: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAxKQ8PSlygUy4WyBq/P0GWC/25n62rayNAA5GA0Rz9vqXLJlQyWvJjOdAIyL2ZA31sXUsG+yoDNtY5mBfuv/pJeNvQNNTf2lIUlt478ojMEebMPFILtU2JhVdnygN4LxzsQmfLlnxytz9rMtlDA3b3U6TJ7Dt9PpV2v5VDE285UvXTmymi6yvORXxljo7w0V2XJtIUENvBk7tJOxA0FB/e8Lh9QdmQ3+T3QDt4oqYxDHGzlKZHrhf0EKrBQNqgS5XQf1YWXcl0kTEkOYa5vr8+hW10kQB/TlBchkp5JhDuezjHUJaCrWYNgtSzCyRpWJLvZQtvFT+MShx+RYXDKpGvw== tyokone
    - username: siikakala
      key: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAIEArsbdE9PSzz//6pJ3xqvReDJqgJMKbdeg7O9nE8PaPp2/ECWw3tnZk8/0csKgUrZFyOQgFasim3qUs/GgWmh4YhoKWt4yEnKxsF1UqPRSE2oKbewd118qx0s1L3HRw9JZLbnuFmtn48+qRjK/j5gLUMz3fo2JEJrYx0o1VENAmgM= siika@meguro
    - username: siikakala
      key: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAv37o2q59hjRsxrce12XVI1E9oWD0ocLBtCeVUOTv+0S1nmaa+kNT4NKaIzymLNNs7+oBondeZrAGB9brplare26sgFwZtnkarAOS1xPa7SGhD0XSQRYvb1lQfdx0du5OeyU1+sKjhMk+bJqQdhjsYlFzhUXwtbr2fx+R7vfJefIy4pMJ59TVG79vILM9u/3NItbTJyTDvn5s8OIcolhVNatJAHe2gs/pwQY5eUHCyYfYXU7+DIH/ZbH5q+Iyy3ejDISWYYj60E5lgDpwcWLSfId5g5Gmjkx/8vaOu0UA+6FJlX/Et6uBCSDEVlFkQ/FkfiHcLvh1YwB/mHmzENeVpQ== miyakojima
    - username: siikakala
      key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDySCgRhcPEG71WlxmXNz5VZLmK6iajqcY16q+dEK1PRNHcNb14jkxhka4sxQS4+QEeep7DhdlcvVXHuet+1CWY4oGyo6ETIMv18RfQjazzKWfJlpjnTPZLaC0U+gHtUdi/fzwPe7BZ6G6bbJ6ITdcD7E+lHas1n6axsPDCCkuT19FDPZm5JBEU/G8fRzxMOc1gGHN1cELD6NhnFZ6f4AarxChT8ac9t24ZmuQP0JbGDcx/0KPBHNS3FMa4JCKiCX8Ra1UpcX4c0JyjNqlUS4LPYRGX97GPNoULsssLjk/4qNqwnHtazQEHbhVdSJxmFgNBESlyv+IlYDRPMkbhrb1Z siika@higashinari

    - username: lmmz
      key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDicvKLwVld3UxE4Z25Vv1emYMlhBQndv3qEHor6//6CurUbY4phdq2RdsGRrCHs71jFPPxsCwU2wyop4cANrSjBnUlQzmdwm2MqO5cl5TzvdWNViCzBpaBuqCx8IIWK5mjYWpyR9Dd5+LiCL+ZnqvKfGyQdZFHGgq4DY/mPxBtA+lLzalF83A0QVJmiwr1hPKYnMurQUmy/DVbiJPMfQfqjYSMG4WRHq5VXpEdEmuaMjK778Zx0N+gzP/c38Lol13y53OZaNedArcaY3WbqVCLWvLVzmg8o4U10Ap8iyiKxAPXz2tW/nc3r1XsVO3LXczzgs9DJQ28JjtXR/s66kjtBg95jnc/+dQe/hFt2p9n2efAqalC64W/XCWnkeA88mNtV7+ZgzydsT5V4ANyf50LPlk5uOLUBM6xyrGN4LTy3Q/c2NgYa4y21v/lcleqR4+KgAsTsuxKQ6/pCNU67eoe2NcOh1rCFkKBZXcznRfmX3kLkB+mP7l6KOot0AUSpQCj7Nfb66PZ2BmDnP7O+BfczhuwVbuKI3KZgLj/03iz7GP8r1HlMIKkHKpqZ5LHVBkIle6TMPHR2MXJ7mvvFqY3lc2/C+kM12Yqhi0NO++zc8KgQbsXIm9QfPBTr6iwMuSrkY31lxq1tRIqgllmreqNIemrx1T3rd5cmP03g51NwQ== mlammi@airheadbook.local
    - username: lmmz
      key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5bdGtauorr8uOtFG/KNmdgpeAN/lwezoPpMRf9BE2fL0fcoYrjo5HdilyVGw4UL/I6GjRssFdye16HHb2MJLVIR95CCNImPx9VpzPQocrXA4q0eB1m+n/lmkQ1kSQv2tXskRjDOUU27UCjfX+DwHXOhIjOPhEz2JrtINrIP6Sxy9mHEh6LdI6oy5GPKRY+Sg13WNfz2udo693awV+LlCXNQAYw59fGvSl9Bcu/iqjA8d9NPgY82hdHARpmxzvMowfEeqPmh0m2wdQ+ZsS3iJIIBUGjOomBcyO+ydbOVIj71ocxpfwtMLb8NMiKh1TUlCgve7NAGB1haSMJMn34qdVUB4q9C2j3291Idj+o7d4OOWsTp00H3miSlM8Timub3rHguPkAXP/Me1F1RyOd778jf9LYfj7Z3ydB0j4Cg5GjLWIkTtJ8Ahu2vdLe3tz+3cmImJIdOo2JqwmyRvowBPZxFh74AiZigKLq4IJqkEwBguYVAAWxB6ALpgFdIhOWWrHKFNJetOz4vNV9eDe5Rc0VkGmzCCtaaWzxEOkYXFvnD4U2rle9dnvKSX/+1ogZ3cC7zXsapJSnfefYELtkiv8nmuI+W0snn0q+3Tjr/gAaup/AzlYq0d/Io5DqFN566IloFXtcFopP8iQLjigsLzDtSM/4Zk98rs2DhVKFsYRyw== lmmz@cutter.lmmz.net

    - username: codez
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII5EpTml0k7/6WDsikL3CIIGyDriYGpwAKTd6wjS6nZh osaka
    - username: codez
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA5ViSwxcxnqHFpkQlyCUvjTyig0w9uhEmxDH6fTjz4c himeji

    - username: aketzu
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP4tvwQlqmnoGSmTLx11lkOgR8NM0f0jHtz1uIRFqdD7 akolehma@ampere
    - username: aketzu
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHPXMznOJ+G413wPIMw2M6EFEd64+EQZqSUgsCKiV4sp akolehma@kelvin.aketzu.net

    - username: root
      key: "{{ jenkinslave_ssh_public_key_data }}"

- name: set backup public keys
  authorized_key:
    user: root
    key: "{{ item.key }}"
    key_options: 'from="{{ item.from_ip }}"'
  with_items: "{{ base_backup_public_keys }}"
  tags:
    - base
    - base-backup
