- name: create local admin users
  user:
    append: yes
    groups: sudo
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    shell: /bin/bash
  with_items: "{{ base_admin_users }}"
  tags:
    - base
    - base-admins

- name: set local admin private keys
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.key }}"
  tags:
    - base
    - base-admins
  with_items: "{{ base_authorized_keys }}"

- name: remove obsolete local admin private keys
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.key }}"
    state: absent
  tags:
    - base
    - base-admins
    - base-admins-ssh-keys-to-remove
  with_items: "{{ base_authorized_keys_to_remove }}"

- name: set jenkinslave private keys
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.key }}"
  tags:
    - base
  with_items:
    - username: root
      key: "{{ jenkinslave_ssh_public_key_data }}"

- name: set backup public keys
  authorized_key:
    user: root
    key: "{{ item.key }}"
    key_options: 'from="{{ item.from_ip }}"'
  with_items: "{{ base_backup_public_keys }}"
  tags:
    - base
    - base-backup
