- name: install ufw
  apt:
    name: ufw

- name: allow ssh in firewall
  ufw:
    rule: allow
    name: OpenSSH

- name: enable firewall
  ufw:
    state: enabled
    policy: reject
    direction: incoming
