---
- import_tasks: dns.yml
- import_tasks: locale.yml
- import_tasks: ssh.yml
- import_tasks: apt.yml
# - import_tasks: admins.yml  # moved to admins role
- import_tasks: firewall.yml
- import_tasks: backup.yml
