#!/bin/bash
set -xue
psql << SUPERHOT
CREATE USER $POSTGRES_BARMAN_DB_USER SUPERUSER PASSWORD '$POSTGRES_BARMAN_DB_PASSWORD';
CREATE USER $POSTGRES_BARMAN_DB_STREAMING_USER REPLICATION PASSWORD '$POSTGRES_BARMAN_DB_STREAMING_PASSWORD';
SUPERHOT
